version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/todo-loopback:cached
    ports:
      - '3001}:3000'
    command: sleep infinity
    env_file:
      - ../.env.dev
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - ../.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_DATABASE:-todo_db}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p${DB_ROOT_PASSWORD}',
        ]
      timeout: 10s
      retries: 10
    volumes:
      - mysql-dev-data:/var/lib/mysql

volumes:
  mysql-dev-data:
